// ─────────────────────────────────────────────────────────────
//  TaniPro — Mock Data
// ─────────────────────────────────────────────────────────────

export const mockProducts = [
  {
    id: "prod_001",
    farmerId: "user_farmer_001",
    farmerName: "Budi Santoso",
    farmerProvince: "Jawa Barat",
    name: "Beras Pandan Wangi Premium",
    description: "Beras organik kualitas premium dari sawah Cianjur, harum dan pulen.",
    price: 14500,
    stock: 5000,
    isPreOrder: false,
    category: "GRAINS",
    weightPerUnit: 1,
    volumePerUnit: 0.0015,
    organicCert: true,
    harvestDate: "2024-01-15",
    imageUrl: "/images/beras.jpg",
    rating: 4.9,
    sold: 1240,
  },
  {
    id: "prod_002",
    farmerId: "user_farmer_002",
    farmerName: "Siti Rahayu",
    farmerProvince: "Jawa Tengah",
    name: "Cabai Merah Keriting",
    description: "Cabai segar langsung dari kebun, tingkat kepedasan tinggi.",
    price: 38000,
    stock: 800,
    isPreOrder: false,
    category: "VEGETABLES",
    weightPerUnit: 1,
    volumePerUnit: 0.002,
    organicCert: false,
    harvestDate: "2024-01-20",
    imageUrl: "/images/cabai.jpg",
    rating: 4.7,
    sold: 356,
  },
  {
    id: "prod_003",
    farmerId: "user_farmer_003",
    farmerName: "Ahmad Fauzi",
    farmerProvince: "Jawa Timur",
    name: "Jagung Manis Super Sweet",
    description: "Jagung manis varietas super sweet, ideal untuk olahan pangan.",
    price: 6500,
    stock: 12000,
    isPreOrder: false,
    category: "GRAINS",
    weightPerUnit: 1,
    volumePerUnit: 0.003,
    organicCert: true,
    harvestDate: "2024-01-18",
    imageUrl: "/images/jagung.jpg",
    rating: 4.8,
    sold: 2100,
  },
  {
    id: "prod_004",
    farmerId: "user_farmer_001",
    farmerName: "Budi Santoso",
    farmerProvince: "Jawa Barat",
    name: "Kedelai Lokal Edamame",
    description: "Kedelai edamame segar, cocok untuk ekspor dan industri snack.",
    price: 18000,
    stock: 0,
    isPreOrder: true,
    preOrderDays: 14,
    category: "GRAINS",
    weightPerUnit: 1,
    volumePerUnit: 0.0012,
    organicCert: false,
    harvestDate: null,
    imageUrl: "/images/kedelai.jpg",
    rating: 4.6,
    sold: 890,
  },
  {
    id: "prod_005",
    farmerId: "user_farmer_004",
    farmerName: "Dewi Kurniawati",
    farmerProvince: "Sulawesi Selatan",
    name: "Kakao Fermentasi Grade A",
    description: "Biji kakao premium terfermentasi 5 hari, aroma kompleks dan kaya.",
    price: 52000,
    stock: 2000,
    isPreOrder: false,
    category: "SPICES",
    weightPerUnit: 1,
    volumePerUnit: 0.0008,
    organicCert: true,
    harvestDate: "2024-01-10",
    imageUrl: "/images/kakao.jpg",
    rating: 5.0,
    sold: 445,
  },
  {
    id: "prod_006",
    farmerId: "user_farmer_002",
    farmerName: "Siti Rahayu",
    farmerProvince: "Jawa Tengah",
    name: "Bawang Merah Brebes",
    description: "Bawang merah asli Brebes, ukuran seragam dan tahan lama.",
    price: 28000,
    stock: 3500,
    isPreOrder: false,
    category: "VEGETABLES",
    weightPerUnit: 1,
    volumePerUnit: 0.0013,
    organicCert: false,
    harvestDate: "2024-01-19",
    imageUrl: "/images/bawang.jpg",
    rating: 4.8,
    sold: 1567,
  },
  {
    id: "prod_007",
    farmerId: "user_farmer_005",
    farmerName: "Hendra Wijaya",
    farmerProvince: "Kalimantan Timur",
    name: "Lada Hitam Putussibau",
    description: "Lada hitam premium dari Kalimantan Timur, aroma tajam dan pedas.",
    price: 85000,
    stock: 600,
    isPreOrder: false,
    category: "SPICES",
    weightPerUnit: 1,
    volumePerUnit: 0.0007,
    organicCert: true,
    harvestDate: "2024-01-05",
    imageUrl: "/images/lada.jpg",
    rating: 4.9,
    sold: 230,
  },
  {
    id: "prod_008",
    farmerId: "user_farmer_003",
    farmerName: "Ahmad Fauzi",
    farmerProvince: "Jawa Timur",
    name: "Mangga Harum Manis",
    description: "Mangga harum manis Probolinggo, manis legit dan aromanya menyerbak.",
    price: 22000,
    stock: 1500,
    isPreOrder: false,
    category: "FRUITS",
    weightPerUnit: 1,
    volumePerUnit: 0.0025,
    organicCert: false,
    harvestDate: "2024-01-22",
    imageUrl: "/images/mangga.jpg",
    rating: 4.7,
    sold: 780,
  },
];

export const mockOrders = [
  {
    id: "ord_001",
    buyerId: "user_buyer_001",
    buyerName: "PT. Sumber Makmur",
    farmerId: "user_farmer_001",
    farmerName: "Budi Santoso",
    totalAmount: 72500000,
    platformFee: 5075000,
    status: "COMPLETED",
    esgCarbonSaved: 42.3,
    createdAt: "2024-01-10T08:30:00Z",
    items: [{ name: "Beras Pandan Wangi", qty: 5000, unit: "kg" }],
  },
  {
    id: "ord_002",
    buyerId: "user_buyer_002",
    buyerName: "CV. Rempah Nusantara",
    farmerId: "user_farmer_002",
    farmerName: "Siti Rahayu",
    totalAmount: 30400000,
    platformFee: 2128000,
    status: "ESCROW_HELD",
    esgCarbonSaved: 18.7,
    createdAt: "2024-01-18T14:00:00Z",
    items: [{ name: "Cabai Merah Keriting", qty: 800, unit: "kg" }],
  },
  {
    id: "ord_003",
    buyerId: "user_buyer_001",
    buyerName: "PT. Sumber Makmur",
    farmerId: "user_farmer_004",
    farmerName: "Dewi Kurniawati",
    totalAmount: 104000000,
    platformFee: 7280000,
    status: "SHIPPED",
    esgCarbonSaved: 63.1,
    createdAt: "2024-01-20T10:00:00Z",
    items: [{ name: "Kakao Fermentasi Grade A", qty: 2000, unit: "kg" }],
  },
];

export const mockShipments = [
  {
    id: "ship_001",
    orderId: "ord_001",
    vehicleType: "FUSO",
    driverName: "Eko Prasetyo",
    driverPhone: "0812-3456-7890",
    licensePlate: "B 1234 KP",
    trackingStatus: "DELIVERED",
    estimatedTime: "2024-01-12T16:00:00Z",
    totalWeightKg: 5000,
    totalVolumeM3: 7.5,
    loadEfficiency: 87,
    currentLat: -6.2088,
    currentLng: 106.8456,
  },
  {
    id: "ship_002",
    orderId: "ord_002",
    vehicleType: "CDD",
    driverName: "Joko Susanto",
    driverPhone: "0813-9876-5432",
    licensePlate: "D 5678 AB",
    trackingStatus: "IN_TRANSIT",
    estimatedTime: "2024-01-22T14:00:00Z",
    totalWeightKg: 800,
    totalVolumeM3: 1.6,
    loadEfficiency: 72,
    currentLat: -6.9175,
    currentLng: 107.6191,
  },
  {
    id: "ship_003",
    orderId: "ord_003",
    vehicleType: "FUSO",
    driverName: "Rendi Saputra",
    driverPhone: "0878-1122-3344",
    licensePlate: "L 9012 FG",
    trackingStatus: "OUT_FOR_DELIVERY",
    estimatedTime: "2024-01-23T10:00:00Z",
    totalWeightKg: 2000,
    totalVolumeM3: 1.6,
    loadEfficiency: 91,
    currentLat: -7.2575,
    currentLng: 112.7521,
  },
];

export const mockFarmers = [
  { id: "user_farmer_001", name: "Budi Santoso",    province: "Jawa Barat",      products: 4, revenue: 128500000, points: 1840, status: "ACTIVE"  },
  { id: "user_farmer_002", name: "Siti Rahayu",     province: "Jawa Tengah",     products: 3, revenue: 89200000,  points: 920,  status: "ACTIVE"  },
  { id: "user_farmer_003", name: "Ahmad Fauzi",     province: "Jawa Timur",      products: 5, revenue: 201000000, points: 2340, status: "ACTIVE"  },
  { id: "user_farmer_004", name: "Dewi Kurniawati", province: "Sulawesi Selatan",products: 2, revenue: 156000000, points: 1560, status: "ACTIVE"  },
  { id: "user_farmer_005", name: "Hendra Wijaya",   province: "Kalimantan Timur",products: 3, revenue: 67800000,  points: 780,  status: "PENDING" },
];

export const mockBuyers = [
  { id: "user_buyer_001", name: "PT. Sumber Makmur",    company: "PT. Sumber Makmur",    totalSpent: 345000000, points: 3450, orders: 12, status: "ACTIVE" },
  { id: "user_buyer_002", name: "CV. Rempah Nusantara", company: "CV. Rempah Nusantara", totalSpent: 189000000, points: 1890, orders: 7,  status: "ACTIVE" },
  { id: "user_buyer_003", name: "PT. Pangan Jaya",      company: "PT. Pangan Jaya",      totalSpent: 520000000, points: 5200, orders: 18, status: "ACTIVE" },
];

export const mockRevenueData = [
  { month: "Agu", revenue: 234, orders: 18 },
  { month: "Sep", revenue: 312, orders: 24 },
  { month: "Okt", revenue: 289, orders: 22 },
  { month: "Nov", revenue: 401, orders: 31 },
  { month: "Des", revenue: 378, orders: 29 },
  { month: "Jan", revenue: 512, orders: 41 },
];

export const mockESGData = [
  { month: "Agu", co2Saved: 128, routeKm: 4200  },
  { month: "Sep", co2Saved: 156, routeKm: 5100  },
  { month: "Okt", co2Saved: 143, routeKm: 4800  },
  { month: "Nov", co2Saved: 198, routeKm: 6500  },
  { month: "Des", co2Saved: 187, routeKm: 6100  },
  { month: "Jan", co2Saved: 241, routeKm: 7900  },
];

// ── Utility helpers ───────────────────────────────────────────

export const formatIDR = (amount: number): string =>
  new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", minimumFractionDigits: 0 }).format(amount);

export const formatNumber = (n: number): string =>
  new Intl.NumberFormat("id-ID").format(n);

export const categoryLabel: Record<string, string> = {
  GRAINS:      "Biji-bijian",
  VEGETABLES:  "Sayuran",
  FRUITS:      "Buah-buahan",
  SPICES:      "Rempah-rempah",
  LIVESTOCK:   "Ternak",
  AQUACULTURE: "Perikanan",
};

export const statusLabel: Record<string, { label: string; color: string }> = {
  PENDING:      { label: "Menunggu",    color: "badge-amber"   },
  ESCROW_HELD:  { label: "Escrow",      color: "badge-blue"    },
  SHIPPED:      { label: "Dikirim",     color: "badge-blue"    },
  COMPLETED:    { label: "Selesai",     color: "badge-emerald" },
  CANCELLED:    { label: "Dibatalkan",  color: "badge-red"     },
  PREPARING:        { label: "Persiapan",       color: "badge-amber"   },
  IN_TRANSIT:       { label: "Dalam Perjalanan", color: "badge-blue"    },
  ARRIVED_HUB:      { label: "Di Hub",           color: "badge-blue"    },
  OUT_FOR_DELIVERY: { label: "Menuju Tujuan",    color: "badge-emerald" },
  DELIVERED:        { label: "Terkirim",         color: "badge-emerald" },
};
